spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sixthdb?useEncoding=utf8&useSSL=true
    username: root
    password: 123456
  freemarker:
    template-loader-path: classpath:web/
    cache: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
mybatis:
  type-aliases-package: com.wang.sixthdemo.domain
  mapper-locations: classpath:mapper/*.xml
