spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fifthdb?useEncoding=utf8&useSSL=true
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.wang.fifth.domain
  mapper-locations: classpath:mapper/*.xml