spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thirddb?characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  data:
    web:
      pageable:
        default-page-size: 5
        page-parameter: pageNumber
        size-parameter: pageSize
      sort:
        sort-parameter: orderBy